version: "3"

services:
  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-20-may-2022/motion-backend/team-2-2:latest
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - ./env/dev.env
    command: "sh /scripts/dev.sh"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ./env/dev.env
    ports:
      - 5555:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: