# Generated by Django 4.0.5 on 2022-06-28 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_following_users_user_is_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_fr_list',
            field=models.ManyToManyField(blank=True, related_name='current_user_fr_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
