# Generated by Django 4.0.5 on 2022-06-28 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_banner_user_job_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='current_user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='things_user_likes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Interest'),
        ),
    ]
