# Generated by Django 4.0.5 on 2022-06-28 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_friends_user_things_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends_of',
            field=models.ManyToManyField(blank=True, related_name='friends_of_friends_current_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
