# Generated by Django 4.0.5 on 2022-06-29 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_friends_fr_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends_fr_list',
            new_name='friends_fr_list_sender',
        ),
        migrations.AddField(
            model_name='user',
            name='friends_fr_list_receiver',
            field=models.ManyToManyField(blank=True, related_name='current_user_received_fr_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
