# Generated by Django 4.0.5 on 2022-06-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_friends_fr_list_user_friends_fr_list_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_received_fr_request',
            field=models.BooleanField(default=False),
        ),
    ]
