# Generated by Django 4.0.5 on 2022-06-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_has_received_fr_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_received_fr_request',
        ),
    ]
