name: motionbackend
dependencies:
  - python=3.10.4
  - pip=21.2.4
  - psycopg2
  - pip:
     - django==4.0.5
     - djangorestframework==3.13.1
     - djangorestframework-simplejwt==5.2.0
     - drf-yasg==1.20.0
     - Pillow==9.1.1
     - flake8==4.0.1
     - gunicorn
     - django-filter