# Generated by Django 4.0.5 on 2022-06-30 12:58

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('code', models.IntegerField(default=registration.models.code_generator, max_length=5)),
            ],
        ),
    ]
