# Generated by Django 4.0.5 on 2022-06-29 08:19

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default=registration.models.code_generator, max_length=5),
        ),
    ]
