# Generated by Django 4.0.5 on 2022-06-30 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='liked_things',
            field=models.ManyToManyField(blank=True, related_name='things_user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
